name: listview_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/img1.png
    - assets/images/img2.png
    - assets/images/img3.png
    - assets/images/img4.png
    - assets/images/img5.png
    - assets/images/img6.png
    - assets/images/img7.png
    - assets/images/img8.png
    - assets/images/img9.png
    - assets/images/img10.png
